# Site settings
title: ramgop
email: contact@ramgop.com
url: https://ramgop.com
description: "Developer looking for a minimalist life with family"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: ramgop

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/ramgop
  - title: linkedin
    url: https://www.linkedin.com/in/ramesh-gopalakrishnan-83652b74/

# Build settings
markdown: kramdown
permalink: pretty
